# Generated by Django 4.0.5 on 2022-06-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('retext', models.CharField(max_length=255)),
                ('fields', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
